Document: squeal
Title: Debian squeal Manual
Author: <insert document author here>
Abstract: This manual describes what squeal is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/squeal/squeal.sgml.gz

Format: postscript
Files: /usr/share/doc/squeal/squeal.ps.gz

Format: text
Files: /usr/share/doc/squeal/squeal.text.gz

Format: HTML
Index: /usr/share/doc/squeal/html/index.html
Files: /usr/share/doc/squeal/html/*.html
